export enum EducationEnum {
    ELEMENTARY_SCHOOL = 'ELEMENTARY_SCHOOL',
    HIGH_SCHOL = 'HIGH_SCHOL',
    ASSOCIATES_DEGREE = 'ASSOCIATES_DEGREE',
    BACHELORS_DEGREE = 'BACHELORS_DEGREE',
    MASTERS_DEGREE = 'MASTERS_DEGREE',
    DOCTORATE_DEGREE = 'DOCTORATE_DEGREE'
}
