export enum MaritalStatusEnum {
    SINGLE = 'SINGLE',
    ENGAGED = 'ENGAGED',
    CIVIL_UNION = 'CIVIL_UNION',
    MARRIED = 'MARRIED',
    SEPARATED = 'SEPARATED',
    DIVORCED = 'DIVORCED',
    WIDOWED = 'WIDOWED'
}
